security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        default:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            logout:
                path: /logout
            oauth:
                resource_owners:
                    twitter: /login/callback
                login_path: /
                use_forward: false
                failure_path: /
                success_handler: App\Security\AuthenticationSuccessHandler
                oauth_user_provider:
                    service: App\Security\UserProvider

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/choose-message, roles: ROLE_USER }
