version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - '2501:80'
        volumes:
            - .:/code
            - ./config/docker/nginx/nginx.conf:/etc/nginx/nginx.conf

    redis:
        image: redis:latest
        command: bash -c "redis-server --appendonly yes"
        ports:
            - '2502:6379'
        volumes:
            - ./var/redis:/data
